### ISSUE TITLE
Cannot choose bright models

### ISSUE THREAD

**Issue by miquecg** [tosher/q2textures#2]
Hi,

Thanks for the effort of putting together so many good resources for an old classic :wink: So far I've only had one issue with one of these paks. I cannot see/choose bright models in players menu. Maybe I'm missing something.

q2pro startup logs:
```
------- FS_Init -------
Current search path:
./baseq2/pak99_textures.pak (1820 files)
./baseq2/pak98_pics.pak (58 files)
./baseq2/pak97_models_bright.pak (135 files)
./baseq2/pak97_models.pak (123 files)
./baseq2/pak95_v_models.pak (27 files)
./baseq2/pak2.pak (2 files)
./baseq2/pak1.pak (279 files)
./baseq2/pak0.pak (3307 files)
./baseq2
5751 files in PAK files
-----------------------
```

**Comment by tosher** [comment]
Just remove `./baseq2/pak97_models.pak ` - only one of two models-paks must be in baseq2 folder.

**Comment by miquecg** [comment]
Thanks :ok_hand:
